name: Cleanup Conda Channel

on:
  schedule:
    - cron: '0 3 * * 0'  # Weekly on Sunday at 03:00 UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Conda channel (pages branch)
        uses: actions/checkout@v4
        with:
          ref: pages

      - name: Checkout main branch (for pkg_versions)
        uses: actions/checkout@v4
        with:
          path: main
          ref: main
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
      
      - name: Install conda-build (for conda index)
        run: conda install -y -c conda-forge conda-index

      - name: Find and keep only latest versions
        run: |
          echo "Collecting files to keep based on version files..."
          KEEP_PATTERNS=""

          for VERSION_FILE in main/PKG_VERSIONS/*.txt; do
            PKG_NAME=$(basename "$VERSION_FILE" .txt)
            VERSION=$(cat "$VERSION_FILE" | tr -d 'v')  # remove leading v
            PATTERN="${PKG_NAME}-${VERSION}*"
            echo "Keeping pattern: $PATTERN"
            KEEP_PATTERNS="${KEEP_PATTERNS} $PATTERN"
          done

          echo "Deleting unmatched conda packages..."
          for FILE in $(find . -type f \( -name '*.tar.bz2' -o -name '*.conda' \)); do
            BASENAME=$(basename "$FILE")
            MATCHED=false
            for PATTERN in $KEEP_PATTERNS; do
              if [[ "$BASENAME" == $PATTERN ]]; then
                MATCHED=true
                break
              fi
            done

            if [ "$MATCHED" = false ]; then
              echo "Deleting $FILE"
              rm "$FILE"
            fi
          done
      - name: Remove main folder
        run: rm -rf main
    
      - name: Run BFG to remove all old binary files
        run: |
              curl -L https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar -o bfg.jar
              java -jar bfg.jar --delete-files '*.tar.bz2'
              rm bfg.jar
              git reflog expire --expire=now --all
              git gc --prune=now --aggressive
              git push origin pages --force


      - name: Rebuild Conda index
        run: conda index .

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-cleanup old Conda packages (keep latest only)"
            git push origin pages
          fi
